eth1_client_name: geth
eth1_image_name: parithoshj/geth:merge-893c372

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"

geth_init_args: >
  --datadir=/eth1data init /networkdata/genesis.json

eth1_start_args: >
  --datadir=/eth1data
  --networkid=1337402 --catalyst
  --http --http.api "engine,net,eth"
  --http.port {{eth1_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws --ws.api "net,eth,engine"
  --ws.port={{eth1_ws_rpc_port}}
  --ws.addr 0.0.0.0
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --vmodule=rpc=5
  {% if (eth1_bootnode_enode is defined) and eth1_bootnode_enode %}
  --bootnodes "{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}

eth1_user_id: "1000:1000"

#  ./go-ethereum/build/bin/geth --datadir=./merge-devnet-1 init genesis.json
# ./go-ethereum/build/bin/geth --datadir=./merge-devnet-1 --ethash.dagdir=./merge-devnet-0/ethash --catalyst --mine --miner.threads=1 --miner.etherbase=0xfb969eb20eca70c2800103bbb0d3757bc60f918a --http --http.corsdomain='*' --http.addr="0.0.0.0" --nat extip:137.184.108.205 --networkid=1337402 console
# ./go-ethereum/build/bin/geth --datadir=./merge-devnet-1 --ethash.dagdir=./merge-devnet-0/ethash --catalyst --http.api="engine,net,eth" --http --http.corsdomain='*' --http.addr="0.0.0.0" --nat extip:137.184.108.205 --networkid=1337402 console