##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"

github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo
  - skylenet
  - samcm

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551

eth1endpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: mainnet-shadow-fork-2
chainID: 1
terminal_total_difficulty: "47074600000000000000000"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-Ly4QAQN8Wf5DjiU949EhsLKUd92m9MP3siwjWPIpQsak6JIAsY1cuh9GuDBcAIRWMrPHBb-MMtY5PicvsXy_r-cAkABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAnl3hJIQAQJQoAAAAAAAAAgmlkgnY0gmlwhKRcp_uJc2VjcDI1NmsxoQO-nLwE91HG7Djhf4wdlj7jpb6yOOeqnj9Rz7Cw51JzkIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-KG4QOuMl4wEdcvaTBiTj54rJ4VvTyAdIiNpqiKi18KDRUW_C0zK9Gam2oKNUgLgSfaAZl4MvsCBtSSEIideqwehdjUDhGV0aDKQJ5d4SSEAECUKAAAAAAAAAIJpZIJ2NIJpcISd5h6AiXNlY3AyNTZrMaECoBab1nZWhfWh7gB4vx67VJdLpbo8brWFGMvzeL9gEtiDdGNwgiMog3VkcIIjKA"
  - "enr:-MK4QHHPd8bdSHvS8NBC9IcXjU7hRt_j9s1Vt6FjiqZ1iFrgFPLsvzTPZK8euy-xnNz-7Y7cJtS_JVFsg6D4XKCujHKGAYBMxEMQh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAnl3hJIQAQJQoAAAAAAAAAgmlkgnY0gmlwhKRcogaJc2VjcDI1NmsxoQMy5nY1vyk2F3mozq6B7-CSiMzKNmYpMPuofYtkSKBkgIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"

eth1_bootnode_enode:
  - "enode://be1127ae8f9522047fa92eeebf2d4922e1be94336ddd678b4829e512331af9463dcd24c2ff92423ef5cb5f654692a66bfd03a97ebca9e3124da14ca401d9e0f6@164.92.128.236:30303"
  - "enode://18ceab489f1e641ff2e6beff3c9229ec40bededd306ad88dcd29ff3deed6e37dff518e69093210cb44d6a84984e1793b258529b16fa7d3c595a71bba47f2f494@159.65.127.106:30303"
  - "enode://e8ae69887b04640dd0183e72e0fb4e34a453090ef1db8120c9e480509ad7b77d1623d7eb324bb06512a79f2d1d13ba2cf9248deab0070c257d89b7431aad82ee@159.223.29.90:30303"
  - "enode://2822e2111179da200e84896aa477295f2fb29a3c85109b839ed0f8b4b4ac56744feb52f397663fe64cf6ae9f2d339a5189c69a9af84664e567ae4e8d11b3a82a@164.92.162.6:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
push_metrics_enabled: true
remote_write_auth: true
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-2.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-2.json | jq .password') }}"

no_validator_keys: false

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
eth1_engine_port_no_auth: 8550
eth1_engine_port: 8551
eth1_engine_snoop_port: 8560
eth1_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"
eth1_metrics_port: 8002

##############################################
# Command for JSON RPC snooper
##############################################
snoop_command: "./json_rpc_snoop -p {{eth1_engine_snoop_port}} http://127.0.0.1:{{eth1_engine_port}}"
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
eth1_node_dir: "{{home_dir}}/eth1data"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000
firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -s 157.230.27.43 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 157.230.27.43 -j ACCEPT"
