##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo
  - skylenet
  - samcm
  - z3n-chada
  - infosecual
  - jtraglia
  - barnabasbusa

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"
eth1endpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: mainnet-shadow-fork-13
chainID: 1
terminal_total_difficulty: "58314930535569159094272"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-Ly4QEO-AWiSpHDiTAUHmpNRfLRqm4LGORhsEalmlO67ZwjmQzFc9hMecBExMRAJ9TRnqD9YuzZCCWv2m1rXxpyeXQkBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCr1il2IQAQODIAAAAAAAAAgmlkgnY0gmlwhKGcjCKJc2VjcDI1NmsxoQPHIFggs9j6i0Jrjlv_zYMWbsJQ2ixt0Od3pXFhpca8k4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"

eth1_bootnode_enode:
  - "enode://2156ea305f03bbb11fb28fff8236f891ad38e748c9cdac94032576076ad494af834ac05400a0ce7cce8b05af193fd3633452d6b15ea8ccc9f433dd982bc3e8d6@161.156.140.34:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
push_metrics_enabled: true
remote_write_auth: true
eth_metrics_exporter_enabled: true
eth2_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "samcm/ethereum-metrics-exporter:0.16.5"
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-13.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-13.json | jq .password') }}"

no_validator_keys: false
ethstats_url: "ethstats.mainnetshadowfork13.ethdevops.io"
ethstats_password: "mainnetshadowfork13"

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
eth1_engine_port_no_auth: 8550
eth1_engine_port: 8551
eth1_engine_snoop_port: 8560
eth1_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "127.0.0.1:9100"
prometheus_web_listen_address: "127.0.0.1:9101"
eth1_metrics_port: 8002
eth_metrics_exporter_port: 8003

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_eth2_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
eth1_node_dir: "{{home_dir}}/eth1data"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -d 161.156.140.34 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -d 161.156.140.34 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3333 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3334 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3000 -d 161.156.140.34 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 161.156.140.34 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 4000 -s 161.156.140.34 -j ACCEPT"