eth1_client_name: geth
eth1_image_name: parithoshj/geth:triedb-fix-flush-order-5758d1f
execution_endpoint: http://127.0.0.1:{{eth1_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{eth1_engine_snoop_port}} http://127.0.0.1:{{eth1_engine_port}}"

home_dir: "/home/{{ansible_user}}"

eth1_github_external_user_pubkeys:
  - mariusVanDerWijden
  - holiman
  - karalabe

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

geth_init_args: >
  --datadir=/eth1data init /networkdata/genesis.json


eth1_start_args: >
  --datadir=/eth1data
  --networkid={{chainID}}
  --http --http.api "admin,engine,net,eth"
  --http.port {{eth1_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws --ws.api "net,eth,engine"
  --ws.port={{eth1_ws_rpc_port}}
  --ws.addr 0.0.0.0
  --authrpc.port={{eth1_engine_port}}
  --authrpc.addr=0.0.0.0
  --authrpc.vhosts="*"
  --authrpc.jwtsecret=/jwtsecret
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port={{eth1_metrics_port}}
  --vmodule=rpc=5
  --maxpeers=75
  --override.terminaltotaldifficulty={{terminal_total_difficulty}}
  --ethstats={{inventory_hostname}}:{{ethstats_password}}@{{ethstats_url}}
  {% if (eth1_bootnode_enode is defined) and eth1_bootnode_enode %}
  --bootnodes "{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}

eth1_user_id: "1000:1000"

# ./go-ethereum/build/bin/geth --datadir=./goerli-shadow-fork init genesis.json
# ./go-ethereum/build/bin/geth --authrpc.jwtsecret=/home/devops/jwtsecret --datadir=./goerli-shadow-fork --ethash.dagdir=./goerli-shadow-fork/ethash --mine --miner.threads=1 --miner.etherbase=0xfb969eb20eca70c2800103bbb0d3757bc60f918a --http --http.corsdomain='*' --http.addr="0.0.0.0" --http.api="engine,net,eth,debug,txpool"  --nat extip:164.90.177.4 --networkid=5 console
# ./go-ethereum/build/bin/geth --datadir=./goerli-shadow-fork --ethash.dagdir=./goerli-shadow-fork/ethash  --http --http.corsdomain='*' --http.addr="0.0.0.0" --http.vhosts="*" --http.api="engine,net,eth,debug,txpool" --ws --ws.api="eth,net,engine" --ws.port=8546 --ws.addr="0.0.0.0" --rpc.allow-unprotected-txs  --nat extip:164.90.177.4 --networkid=5 console
