##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"

github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo
  - skylenet
  - samcm
  - z3n-chada
  - infosecual
  - jtraglia

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551

eth1endpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: mainnet-shadow-fork-7
chainID: 1
terminal_total_difficulty: "52337651844220509487104"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-Ly4QGWGgf2vlWRRV1nrRHvwRWYRYJYnijCjCFpCxodG8nWYTRksaTSixPEhLjmoC4ivmWGkbmPpC0H4Uyy5b4z8VaYBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCEfltAIQAQMDIAAAAAAAAAgmlkgnY0gmlwhJK-Gc-Jc2VjcDI1NmsxoQN856T24INJcQ8GJpE0BdSMAMEmqZnLp7kyapS9Ekaq3ohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QIc1453NHdFGtydgBVzL6qr9MLhYC8YGV-B9Gcqiwi01UuFbKa1kOvuqBGIGpCEzpZx_elIqfkH5NpeZYgHUHE0Kh2F0dG5ldHOI__________-EZXRoMpBv5qboIgAQMP__________gmlkgnY0gmlwhIbRVX2Jc2VjcDI1NmsxoQJQoBj_Yhk4Y-Ug18qesg__llfzEIlNw4z-nzbv8jMU7IhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QOZsoNbwJmmZ_LCXfaaGEpdT2UypoohKpQwhV2y1qvSCRcji4ltEhP1eEvXvj5G8SSaBje6n73pxjij5NbNstldHh2F0dG5ldHOI__________-EZXRoMpBv5qboIgAQMP__________gmlkgnY0gmlwhKdHBLyJc2VjcDI1NmsxoQLcwq_ig-OMHd5AmVGXu8xr3yPnpSEsUaQql-leUmst54hzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QIw0fxralOpM_PRZQmOKM57F3hMU1jK7O2QkOmkfzH-SI80dPQS7pcXyVAT_f1AwDZublGvM4WQn9qWt-E3-7c5Hh2F0dG5ldHOI__________-EZXRoMpBv5qboIgAQMP__________gmlkgnY0gmlwhKdHQUqJc2VjcDI1NmsxoQNsDeZRx41ETpLEv0biXpLhbGd6JFV1BlWLC9jL4ZDEWYhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"

eth1_bootnode_enode:
  - "enode://470498e8d72dea29e3144006e812d3dd34112c12eb013a908d006c5cf4f88beee8a995a5deb116109412277c20ab835e5bf555cfb490b2f4095bf2d3508f83d4@206.189.1.20:30303"
  - "enode://b5af1186d530ecca81ddc95f5ea4e3285f0fc76dbf7e3008d356f4685b8e16bd48ccfd99ba1957579225d4bbc5ccfaddfc1f3af94cd15c55ba064f480b2a44f8@134.209.85.125:30303"
  - "enode://465243d3417ee83cdd1820352002b3d2b76da7bd5cad4d824350c9dd134c2921e55a2ef75282b030ad1fef077e5eb33d30a4c116cbb1ce1664039b7ae26c33b3@167.71.65.74:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
push_metrics_enabled: true
remote_write_auth: true
eth_metrics_exporter_enabled: true
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "samcm/ethereum-metrics-exporter:0.12.0"
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-7.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/shadow-mainnet-7.json | jq .password') }}"

no_validator_keys: false
ethstats_url: "ethstats.mainnetshadowfork7.ethdevops.io"
ethstats_password: "mainnetshadowfork7"

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
eth1_engine_port_no_auth: 8550
eth1_engine_port: 8551
eth1_engine_snoop_port: 8560
eth1_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"
prometheus_web_listen_address: "0.0.0.0:9101"
eth1_metrics_port: 8002
eth_metrics_exporter_port: 8003

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
eth1_node_dir: "{{home_dir}}/eth1data"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -d 146.190.25.207 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -d 146.190.25.207 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3333 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3334 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 3000 -d 146.190.25.207 -j ACCEPT"
