- name: Stop execution node
  hosts: execution
  gather_facts: true
  serial: 20
  tasks:
    - name: Stop execution node container
      shell: "docker stop {{ execution_container_name }}"
      register: stop_result
      failed_when: "(stop_result.rc >= 1) and not ('No such container' in stop_result.stderr)"
