version: "3.4"
services:
  init_geth:
    image: parithoshj/geth:merge-ac736f9
    container_name: geth_init
    volumes:
      - ./execution_data:/execution_data
      - ../../$TESTNET_NAME/custom_config_data:/custom_config_data
    command: >
      --datadir=/execution_data init /custom_config_data/genesis.json
    network_mode: host
  geth:
    image: parithoshj/geth:merge-ac736f9
    container_name: geth
    depends_on:
      - init_geth
    volumes:
      - ./execution_data:/execution_data
    command: >
      --datadir=/execution_data --networkid=$NETWORK_ID --catalyst --http --http.api "engine,eth" --ws --ws.api "engine,eth" --nat extip:$IP_ADDRESS --bootnodes=$ENODE
    network_mode: host