PRESET_BASE: minimal
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1000
MIN_GENESIS_TIME: 1633698726
GENESIS_FORK_VERSION: 0x10000069
GENESIS_DELAY: 300
ALTAIR_FORK_VERSION: 0x11000070
ALTAIR_FORK_EPOCH: 4
MERGE_FORK_VERSION: 0x12000071
MERGE_FORK_EPOCH: 10
SECONDS_PER_SLOT: 6
SECONDS_PER_ETH1_BLOCK: 14
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 64
ETH1_FOLLOW_DISTANCE: 16
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 32
DEPOSIT_CHAIN_ID: 1337201
DEPOSIT_NETWORK_ID: 1337201
DEPOSIT_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000000000
TERMINAL_TOTAL_DIFFICULTY: 60000000

