##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"

github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo
  - skylenet
  - samcm

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551

eth1endpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: kiln
chainID: 1337802
terminal_total_difficulty: "1000000000000"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-KG4QFkPJUFWuONp5grM94OJvNht9wX6N36sA4wqucm6Z02ECWBQRmh6AzndaLVGYBHWre67mjK-E0uKt2CIbWrsZ_8DhGV0aDKQc6pfXHAAAHAyAAAAAAAAAIJpZIJ2NIJpcISl6LTmiXNlY3AyNTZrMaEDHlSNOgYrNWP8_l_WXqDMRvjv6gUAvHKizfqDDVc8feaDdGNwgiMog3VkcIIjKA"
  - "enr:-MK4QI-wkVW1PxL4ksUM4H_hMgTTwxKMzvvDMfoiwPBuRxcsGkrGPLo4Kho3Ri1DEtJG4B6pjXddbzA9iF2gVctxv42GAX9v5WG5h2F0dG5ldHOIAAAAAAAAAACEZXRoMpBzql9ccAAAcDIAAAAAAAAAgmlkgnY0gmlwhKRcjMiJc2VjcDI1NmsxoQK1fc46pmVHKq8HNYLkSVaUv4uK2UBsGgjjGWU6AAhAY4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"

eth1_bootnode_enode:
  - "enode://c354db99124f0faf677ff0e75c3cbbd568b2febc186af664e0c51ac435609badedc67a18a63adb64dacc1780a28dcefebfc29b83fd1a3f4aa3c0eb161364cf94@164.92.130.5:30303"
  - "enode://d41af1662434cad0a88fe3c7c92375ec5719f4516ab6d8cb9695e0e2e815382c767038e72c224e04040885157da47422f756c040a9072676c6e35c5b1a383cce@138.68.66.103:30303"
  - "enode://91a745c3fb069f6b99cad10b75c463d527711b106b622756e9ef9f12d2631b6cb885f831d1c8731b9bc7177cae5e1ea1f1be087f86d7d30b590a91f22bc041b0@165.232.180.230:30303"
  - "enode://b74bd2e8a9f0c53f0c93bcce80818f2f19439fd807af5c7fbc3efb10130c6ee08be8f3aaec7dc0a057ad7b2a809c8f34dc62431e9b6954b07a6548cc59867884@164.92.140.200:3030"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
thanos_url: "http://thanos.ethdevops.io:19291/api/v1/receive/"
push_metrics_enabled: true

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
eth1_engine_port_no_auth: 8550
eth1_engine_port: 8551
eth1_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ ansible_user }}"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
eth1_node_dir: "{{home_dir}}/eth1data"

##############################################
# common log config
##############################################
common_log_options:
  max-file: "10"
  max-size: 30m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file
beacon_log_level: info

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000
firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -s 164.92.130.5 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 164.92.130.5 -j ACCEPT"
