##############################################
# image name and image location
##############################################
eth2_client_name: grandine

beacon_image_name: parithoshj/grandine:v0.2.0-beta3
validator_image_name: parithoshj/grandine:v0.2.0-beta3
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

eth2_github_external_user_pubkeys:


##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{validator_node_dir}}:/validatordata"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  grandine --network kintsugi --eth1-rpc-url {{eth1endpoint}}
  --keystore-dir /validatordata/keys --keystore-password-file /validatordata/secrets


##############################################
# memory limits
##############################################
validator_memory: 2000M
validator_kernel_memory: 2500M
beacon_memory: 5000M
beacon_kernel_memory: 5500M

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "0:0"

separate_validator_process_enabled: false
