##############################################
# generic ansible config information
##############################################
ansible_user: "ubuntu"
github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
eth1endpoint_nimbus: wss://url
eth1endpoint: https://url

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)
execution_engine_endpoint: http://127.0.0.1:8545

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: alpha

# TODO: set TTD
terminal_total_difficulty: 16

# enter bootnodes here if needed
#bootnode_enrs:

##############################################
# metric information
##############################################
# enter pushgateway config if needed
pushgateway_ip: ip-here
push_metrics_enabled: false

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../selected_validator_keys/host_{{eth2_node_index}}"
local_validator_host_archive: "{{inventory_dir}}/../selected_validator_keys/host_{{eth2_node_index}}.tar.gz"

##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ ansible_user }}"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"

##############################################
# common log config
##############################################
common_log_options:
  max-file: "10"
  max-size: 30m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file
beacon_log_level: info

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
hi_peer_count: 25
separate_validator_process_enabled: true