eth1_client_name: geth
eth1_image_name: protolambda/geth:rayonism

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/gethdata"
  - "{{testnet_dir}}/eth1_config.json:/networkdata/eth1_config.json"

geth_init_args: >
  --catalyst
  --datadir "/gethdata/chaindata"
  init "/networkdata/eth1_config.json"

eth1_start_args: >
  --catalyst
  --networkid=702
  --http --http.api net,eth,consensus
  --http.port {{eth1_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws --ws.api net,eth,consensus
  --ws.port={{eth1_ws_rpc_port}}
  --ws.addr 0.0.0.0
  --nodiscover
  --miner.etherbase 0x1000000000000000000000000000000000000000
  --datadir "/gethdata/chaindata"

eth1_user_id: "1000:1000"
