##############################################
# image name and image location
##############################################
eth2_client_name: prysm
beacon_image_name: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.0.0-rc.1
validator_image_name: gcr.io/prysmaticlabs/prysm/validator:v2.0.0-rc.1

# GRPC, not REST JSON
beacon_endpoint: "127.0.0.1:{{beacon_grpc_port}}"

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}/eth2_config.yaml:/custom_config_data/eth2_config.yaml"
  - "{{testnet_dir}}/genesis.ssz:/custom_config_data/genesis.ssz"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}/eth2_config.yaml:/custom_config_data/eth2_config.yaml"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --accept-terms-of-use=true
  --datadir="/beacondata"
  --genesis-state="/custom_config_data/genesis.ssz"
  --chain-config-file="/custom_config_data/eth2_config.yaml"
  --http-web3provider="{{eth1endpoint}}"
  {% if failover_eth1_rpc is defined %}
    --fallback-web3provider={{failover_eth1_rpc}}
  {% endif %}
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
    --bootstrap-node="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --verbosity="{{ beacon_log_level | lower }}"
  --p2p-host-ip={{public_ip_address}}
  --p2p-max-peers={{hi_peer_count}}
  --p2p-udp-port={{beacon_p2p_port}} --p2p-tcp-port={{beacon_p2p_port}}
  --monitoring-host=0.0.0.0 --monitoring-port={{beacon_metrics_port}}
  --rpc-host=0.0.0.0 --rpc-port={{beacon_grpc_port}}
  --grpc-gateway-host=0.0.0.0
  --grpc-gateway-port={{beacon_api_port}}
  --verbosity="trace"
  --enable-debug-rpc-endpoints
  --min-sync-peers 1

validator_start_args: >
  --accept-terms-of-use=true
  --datadir="/validatordata"
  --chain-config-file="/custom_config_data/eth2_config.yaml"
  --beacon-rpc-provider={{beacon_endpoint}}
  --monitoring-host=0.0.0.0 --monitoring-port={{validator_metrics_port}}
  --graffiti="{{graffiti}}"
  --wallet-dir=/validatordata/wallet
  --wallet-password-file="/validatordata/wallet_pass.txt"
##############################################
# memory limits
##############################################
validator_memory: 2000M
validator_kernel_memory: 2500M
beacon_memory: 5000M
beacon_kernel_memory: 5500M

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"