##############################################
# image name and image location
##############################################
cl_client_name: nimbus

beacon_image_name: statusim/nimbus-cl:amd64-v22.9.0
validator_image_name: statusim/nimbus-cl:amd64-v22.9.0
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

cl_github_external_user_pubkeys:
  - zah
  - tersec
  - etan-status

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{validator_node_dir}}:/validatordata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

beacon_log_level: debug
##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --non-interactive=true
  --network="/custom_config_data"
  --max-peers="{{hi_peer_count}}"
  --data-dir="/beacondata"
  --web3-url="{{execution_endpoint}}"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --bootstrap-node="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --udp-port={{beacon_p2p_port}}
  --tcp-port={{beacon_p2p_port}}
  --listen-address=0.0.0.0
  --graffiti="{{graffiti}}"
  --nat="extip:{{ansible_host}}"
  --enr-auto-update=false
  --rest --rest-port={{beacon_api_port}} --rest-address=0.0.0.0
  --metrics --metrics-port={{beacon_metrics_port}} --metrics-address=0.0.0.0
  --log-level="{{ beacon_log_level | upper }}"
  --doppelganger-detection=off
  {% if no_validator_keys != 'true' %}
  --validators-dir="/validatordata/keys"
  --secrets-dir="/validatordata/secrets"
  --suggested-fee-recipient={{fee_recipient}}
  {% endif %}
  --jwt-secret=/jwtsecret
  --dump:on

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:100"
validator_user_id: "1000:100"

# Nimbus currently runs on a combined beacon validator process, future versions will work as separate processes
separate_validator_process_enabled: false
