##############################################
# image name and image location
##############################################
cl_client_name: prysm
beacon_image_name:  gcr.io/prysmaticlabs/prysm/beacon-chain:v3.1.0
validator_image_name: gcr.io/prysmaticlabs/prysm/validator:v3.1.0
# GRPC, not REST JSON
beacon_endpoint: "127.0.0.1:{{beacon_grpc_port}}"

cl_github_external_user_pubkeys:
  - kasey
  - terencechain
  - potuz
  - nisdas

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}:/custom_config_data"

###############################################
## memory limits
###############################################
#beacon_env:
#  MSAN_SYMBOLIZER_PATH: /usr/bin/llvm-symbolizer
#
#validator_env:
#  MSAN_SYMBOLIZER_PATH: /usr/bin/llvm-symbolizer

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --accept-terms-of-use=true
  --datadir="/beacondata"
  --chain-config-file="/custom_config_data/config.yaml"
  --genesis-state="/custom_config_data/genesis.ssz"
  --execution-endpoint="{{execution_endpoint}}"
    {% if (bootnode_enrs is defined) and bootnode_enrs %}
    {% for bootnode_enrs in bootnode_enrs %}
    --bootstrap-node="{{ bootnode_enrs }}"
    {% endfor %}
    {% endif %}
  --verbosity="{{ beacon_log_level | lower }}"
  --min-sync-peers=1
  --pprof
  --p2p-host-ip={{ansible_host}}
  --p2p-max-peers={{hi_peer_count}}
  --p2p-udp-port={{beacon_p2p_port}} --p2p-tcp-port={{beacon_p2p_port}}
  --monitoring-host=0.0.0.0 --monitoring-port={{beacon_metrics_port}}
  --rpc-host=0.0.0.0 --rpc-port={{beacon_grpc_port}}
  --grpc-gateway-host=0.0.0.0
  --grpc-gateway-port={{beacon_api_port}}
  --enable-debug-rpc-endpoints
  --jwt-secret=/jwtsecret
  --suggested-fee-recipient={{ fee_recipient }}
  --contract-deployment-block=14675001
  {% if mev_boost == 'true' %}
  --http-mev-relay="http://127.0.0.1:{{mev_boost_port}}"
  {% endif %}

validator_start_args: >
  --accept-terms-of-use=true
  --datadir="/validatordata"
  --chain-config-file="/custom_config_data/config.yaml"
  --beacon-rpc-provider={{beacon_endpoint}}
  --monitoring-host=0.0.0.0 --monitoring-port={{validator_metrics_port}}
  --graffiti="{{graffiti}}"
  --wallet-dir=/validatordata/wallet
  --wallet-password-file="/validatordata/wallet_pass.txt"
  {% if mev_boost == 'true' %}
  --enable-builder
  {% endif %}

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"

beacon_log_level: debug
separate_validator_process_enabled: true
