##############################################
# image name and image location
##############################################
cl_client_name: teku
beacon_image_name: consensys/teku:22.9.0
validator_image_name: consensys/teku:22.9.0
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

cl_github_external_user_pubkeys:
  - tbenr
  - ajsutton

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{validator_node_dir}}:/validatordata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --network="/custom_config_data/config.yaml"
  --initial-state="/custom_config_data/genesis.ssz"
  --Xee-version=kilnv2
  --data-path="/beacondata"
  --data-storage-mode=PRUNE
  --p2p-enabled=true
  --p2p-advertised-ip={{ansible_host}}
  --p2p-port="{{beacon_p2p_port}}"
  --p2p-advertised-port={{beacon_p2p_port}}
  --logging={{beacon_log_level}}
  --p2p-peer-upper-bound={{hi_peer_count}}
  --ee-endpoint="{{execution_endpoint}}"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --p2p-discovery-bootnodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --metrics-enabled=true --metrics-interface=0.0.0.0 --metrics-port="{{beacon_metrics_port}}"
  --rest-api-enabled=true
  --rest-api-docs-enabled=true
  --rest-api-interface=0.0.0.0
  --rest-api-port="{{beacon_api_port}}"
  --metrics-host-allowlist="*"
  --rest-api-host-allowlist="*"
  --data-storage-non-canonical-blocks-enabled=true
  {% if no_validator_keys != 'true' %}
  --validators-proposer-default-fee-recipient={{fee_recipient}}
  --validators-graffiti="{{graffiti}}"
  --validator-keys="/validatordata/keys:/validatordata/secrets"
  --validators-keystore-locking-enabled=false
  {% endif %}
  --ee-jwt-secret-file="/jwtsecret"
  --Xlog-include-p2p-warnings-enabled
  --Xmetrics-block-timing-tracking-enabled
  --Xprogressive-balances-mode=USED
  {% if mev_boost == 'true' %}
  --builder-endpoint="http://127.0.0.1:{{mev_boost_port}}"
  --validators-builder-registration-default-enabled=true
  {% endif %}

##############################################
# memory limits
##############################################
beacon_env:
  JAVA_OPTS: "-XX:SoftMaxHeapSize=4g -Xmx8g"

# TODO: maybe configure logging style via env var later
#  LOG4J_CONFIGURATION_FILE: "/beacondata/log_config.xml"

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0704"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"

# Teku currently runs on a combined beacon validator process for the merge code, future versions will work as separate processes
separate_validator_process_enabled: false
