##############################################
# image name and image location
##############################################
eth2_client_name: teku
beacon_image_name: consensys/teku:develop
validator_image_name: consensys/teku:develop
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

eth2_github_external_user_pubkeys:
  - tbenr
  - ajsutton

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{validator_node_dir}}:/validatordata"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --network kintsugi
  --data-path "/beacondata"
  --data-storage-mode=PRUNE
  --p2p-enabled=true
  --p2p-advertised-ip={{ansible_host}}
  --p2p-port="{{beacon_p2p_port}}"
  --p2p-advertised-port={{beacon_p2p_port}}
  --logging={{beacon_log_level}}
  --p2p-peer-upper-bound={{hi_peer_count}}
  --eth1-endpoints="{{eth1endpoint}}"
  --Xee-endpoint="{{eth1endpoint}}"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --p2p-discovery-bootnodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --metrics-enabled=true --metrics-interface=0.0.0.0 --metrics-port="{{beacon_metrics_port}}"
  --rest-api-enabled=true
  --rest-api-docs-enabled=true
  --rest-api-interface=0.0.0.0
  --rest-api-port="{{beacon_api_port}}"
  --metrics-host-allowlist="*"
  --rest-api-host-allowlist="*"
  --data-storage-non-canonical-blocks-enabled=true
  --Xvalidators-proposer-default-fee-recipient="0xA18Fd83a55A9BEdB96d66C24b768259eED183be3"
  --validators-graffiti="{{graffiti}}"
  --validator-keys="/validatordata/keys:/validatordata/secrets"
  --validators-keystore-locking-enabled=false

##############################################
# memory limits
##############################################
beacon_memory: 15000M
beacon_kernel_memory: 15500M
validator_memory: 2000M
validator_kernel_memory: 2500M
beacon_env:
  JAVA_OPTS: "-Xmx10000m -Xms10000m"

# TODO: maybe configure logging style via env var later
#  LOG4J_CONFIGURATION_FILE: "/beacondata/log_config.xml"

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0704"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"

# Teku currently runs on a combined beacon validator process for the merge code, future versions will work as separate processes
separate_validator_process_enabled: false