version: "3.4"
services:
  teku_beacon:
    image: consensys/teku:develop
    container_name: teku_beacon
    volumes:
      - ./beacon_data:/consensus_data
      - ../../../$TESTNET_NAME/custom_config_data:/custom_config_data
    command: >
      --network "/custom_config_data/config.yaml"
      --initial-state "/custom_config_data/genesis.ssz"
      --data-path "/consensus_data" --data-storage-mode=PRUNE
      --p2p-enabled=true --eth1-endpoints=http://127.0.0.1:8545
      --Xee-endpoint=http://127.0.0.1:8545
      --p2p-advertised-ip=$IP_ADDRESS --p2p-discovery-bootnodes=$ENR
      --rest-api-enabled=true --rest-api-docs-enabled=true
      --rest-api-interface=0.0.0.0 --rest-api-port=4000
      --rest-api-host-allowlist=* --Xdata-storage-non-canonical-blocks-enabled=true
      --Xnetwork-merge-total-terminal-difficulty=$TOTAL_TERMINAL_DIFFICULTY
      --log-destination=CONSOLE
    network_mode: host