##############################################
# image name and image location
##############################################
eth2_client_name: lodestar

# TODO: switch to merge f2f, but mainnet preset
beacon_image_name: parithoshj/lodestar:merge-155311b
validator_image_name: parithoshj/lodestar:merge-155311b
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

eth2_github_external_user_pubkeys:
  - dapplion
  - wemeetagain
  - tuyennhv
  - g11tech

beacon_env:
  LODESTAR_PRESET: mainnet

validator_env:
  LODESTAR_PRESET: mainnet

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}:/custom_config_data"
##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  beacon
        --rootDir=/beacondata
        --paramsFile=/custom_config_data/config.yaml
        --genesisStateFile=/custom_config_data/genesis.ssz
        {% if (bootnode_enrs is defined) and bootnode_enrs %}
        --network.discv5.bootEnrs="{{ bootnode_enrs | join(',') }}"
        {% endif %}
        --network.connectToDiscv5Bootnodes
        --network.discv5.enabled=true
        --eth1.enabled=true
        --api.rest.port={{beacon_api_port}}
        --eth1.disableEth1DepositDataTracker=true
        --eth1.providerUrls={{execution_engine_endpoint}}
        --execution.urls={{execution_engine_endpoint}}
        --api.rest.enabled=true
        --api.rest.host=0.0.0.0
        --api.rest.api="*"
        --logLevel={{ beacon_log_level | lower }}
        --logLevelFile=debug
        --logFile=/beacondata/beacon.log
        --logRotate
        --logMaxFiles=5
        --enr.ip={{ansible_host}}
        --metrics.enabled
        --metrics.serverPort={{ beacon_metrics_port }}

validator_start_args: >
  validator
   --rootDir=/validatordata
  --paramsFile=/custom_config_data/config.yaml
   --keystoresDir=/validatordata/keystores
   --secretsDir=/validatordata/secrets/
   --server={{beacon_endpoint}}
   --logFile=/validatordata/validator.log
   --logLevelFile=debug
   --logRotate
   --logMaxFiles=5
  --graffiti={{graffiti}}

##############################################
# memory limits
##############################################
validator_memory: 2000M
validator_kernel_memory: 2500M
beacon_memory: 5000M
beacon_kernel_memory: 5500M

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"

separate_validator_process_enabled: true