##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"

github_user_pubkeys:
  - parithosh
  - protolambda
  - ralexstokes
  - djrtwo
  - skylenet

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# eth1 endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8546
# lighthouse uses this
execution_engine_endpoint: http://127.0.0.1:8545

eth1endpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
eth2_network_name: merge-devnet-5
chainID: 1337762
terminal_total_difficulty: "500000000000"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-KG4QOTc757CCrXflRy-PfpOqj9d8gfU2BfAl5g6dPeKD3NUEpO5ZPWrb6yb9z7Kl--K5ZYyTh5UBGFuiP7usjM1ZvYDhGV0aDKQAb0xRmAAEHAyAAAAAAAAAIJpZIJ2NIJpcISPbrKTiXNlY3AyNTZrMaED0VhXD--_yljQbsdQuaX9fmPx17nPjoghW_ktkUjHAZuDdGNwgiMog3VkcIIjKA"
  - "enr:-MK4QAkLLZ0rvDL2z-3UcNsqqFmqv340P-2539L5SONwDnHDEs2IE44oGQgCeSgM3FytIQD7_esjtXOYYW0VLyVINAWGAX9KbEaTh2F0dG5ldHOIAAAAAAAAAACEZXRoMpABvTFGYAAQcDIAAAAAAAAAgmlkgnY0gmlwhES3SFeJc2VjcDI1NmsxoQPZcA1UJ8TH5w7q0EayJA9mK7oTWlni5uqlUQmRVekMOIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-Ku4QPvAW_hoT_-brvCoyWg5Dw5GZLGWoCNjyKv1NPUGNX7yWQdApiWWXudA_uMobwiJhwc7a8XBJZ0qANtuMisHfv0Fh2F0dG5ldHOIAAAAAAAAAACEZXRoMpABvTFGYAAQcDIAAAAAAAAAgmlkgnY0gmlwhIbR-yGJc2VjcDI1NmsxoQK4E-iLa_t-wnMFq3hdcikLWKk2LG0m2jgnDAh_Tm_68oN0Y3CCIyg"
  - "enr:-KG4QISQPuQltCd1kNhXErr2_aw-2Zlll7i-g4UZYGKlExxoAvF7-obg3imiCyt0nxDMhxGM9E0saWbCz4CJ_7s4KMkDhGV0aDKQAb0xRmAAEHAyAAAAAAAAAIJpZIJ2NIJpcISPbvU3iXNlY3AyNTZrMaEDZ4luTNOefRpbt9-f4XEShUH4_S9CACYOIxfaBnCHzKyDdGNwgiMog3VkcIIjKA"
eth1_bootnode_enode:
  - "enode://52a817b840207cb79d2c10fa14794d10b706ad2570bed2dd51a1518b3bd4592657d696960579947634bbf4faf06b03b6610ef2b9ac0355a8bf926de12bf866d2@134.209.253.71:30303"
  - "enode://0336549edd1c96012841d31c06f8de35bcb457268907d197028f99f9da67449cdfadf992007942026427f95516f7dc06ef146c5fcd2569383cab02132457ae87@143.110.245.55:30303"
  - "enode://8f76220e431ef14aa10a6fb2ebe5374976247b6e1c7dda23d6dbded6b4795d940890d770bc3f77455543873b4578be1398e64fb5ba91ad66fb62ed3bd4181b4c@143.110.178.147:30303"
  - "enode://649a3b0ffbe637eaceb648277a9d4c64f00dddfd6caf0b9d34936743b549d89f8be8efbbfbed6d18d43fd8d67591c5c3b5b13bb9a819b732360c0f8eafe6aadb@68.183.72.87:30303"
  - "enode://7b32355d6bea7d995f040c6e032abc24c53b4afafde5dfb6fb100a97540e8894694582eff832a644022f46b5c96e36f81273eb82d0ee284e2e960324530958bb@165.22.92.227:30303"

##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
thanos_url: "http://thanos.ethdevops.io:19291/api/v1/receive/"
push_metrics_enabled: true

##############################################
# ports to configure
##############################################
eth1_rpc_port: 8545
eth1_ws_rpc_port: 8546
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "0.0.0.0:9100"

##############################################
# name of the validator to display
##############################################
graffiti: "{{eth2_client_name}}-{{eth1_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
home_dir: "/home/{{ ansible_user }}"
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
eth1_node_dir: "{{home_dir}}/eth1data"

##############################################
# common log config
##############################################
common_log_options:
  max-file: "10"
  max-size: 30m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file
beacon_log_level: info

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000
firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4000 -s 134.209.253.71 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 134.209.253.71 -j ACCEPT"
