eth1_client_name: nethermind
eth1_image_name: nethermindeth/nethermind:kiln_0.4

eth1_github_external_user_pubkeys:
  - MarekM25

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# websocket with upgrade
eth1endpoint_ws: http://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"

eth1_start_args: >
  --config=kiln
  --datadir="/eth1data"
  --Init.ChainSpecPath="/networkdata/nethermind_genesis.json"
  --Init.WebSocketsEnabled=true
  --JsonRpc.Enabled=true
  --JsonRpc.EnabledModules="net,eth,consensus,engine,subscribe,web3,admin"
  --JsonRpc.Port={{eth1_rpc_port}}
  --JsonRpc.WebSocketsPort={{eth1_ws_rpc_port}}
  --JsonRpc.Host=0.0.0.0
  --Network.DiscoveryPort=30303
  --Network.P2PPort=30303
  --Merge.Enabled=true
  --Merge.FeeRecipient={{fee_recipient}}
  --Merge.TerminalTotalDifficulty={{terminal_total_difficulty}}
  --Init.DiagnosticMode="None"
  --Init.IsMining=true

# run as root, the nethermind image doesn't handle running regular user well
eth1_user_id: "0:0"
