##############################################
# image name and image location
##############################################
eth2_client_name: teku
beacon_image_name: parithoshj/teku:merge-7a246df
validator_image_name: parithoshj/teku:merge-7a246df
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

github_external_user_pubkeys:
  - tbenr
  - ajsutton

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}:/custom_config_data"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  --network "/custom_config_data/config.yaml"
  --initial-state "/custom_config_data/genesis.ssz"
  --data-path "/beacondata"
  --data-storage-mode=PRUNE
  --p2p-enabled=true
  --p2p-advertised-ip={{ansible_host}}
  --p2p-port="{{beacon_p2p_port}}"
  --p2p-advertised-port={{beacon_p2p_port}}
  --logging={{beacon_log_level}}
  --log-destination=CONSOLE
  --log-file="/beacondata/log_outputs"
  --p2p-peer-upper-bound={{hi_peer_count}}
  --eth1-endpoints="{{eth1endpoint}}"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --p2p-discovery-bootnodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --metrics-enabled=true --metrics-interface=0.0.0.0 --metrics-port="{{beacon_metrics_port}}"
  --p2p-discovery-enabled=true
  --p2p-peer-lower-bound=1
  --rest-api-enabled=true
  --rest-api-docs-enabled=true
  --rest-api-interface=0.0.0.0
  --rest-api-port="{{beacon_api_port}}"
  --metrics-host-allowlist="*"
  --rest-api-host-allowlist="*"
  --Xdata-storage-non-canonical-blocks-enabled=true
  --Xnetwork-merge-total-terminal-difficulty={{terminal_total_difficulty}}


validator_start_args: >
  validator-client
  --network=auto
  --data-path="/validatordata"
  --beacon-node-api-endpoint="{{beacon_endpoint}}"
  --validators-graffiti="{{graffiti}}"
  --validator-keys="/validatordata/keys:/validatordata/secrets"

##############################################
# memory limits
##############################################
beacon_memory: 14000M
beacon_kernel_memory: 14500M
validator_memory: 2000M
validator_kernel_memory: 2500M
beacon_env:
  JAVA_OPTS: "-Xmx14000m -Xms14000m"

# TODO: maybe configure logging style via env var later
#  LOG4J_CONFIGURATION_FILE: "/beacondata/log_config.xml"

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0704"
beacon_user_id: "1000:1000"
validator_user_id: "1000:1000"