eth1_client_name: besu
eth1_image_name: hyperledger/besu:22.7.0-SNAPSHOT-openjdk-11-debug-amd64
execution_endpoint: http://127.0.0.1:{{eth1_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{eth1_engine_snoop_port}} http://127.0.0.1:{{eth1_engine_port}}"

home_dir: "/home/{{ansible_user}}"

eth1_memory: 5000M
eth1_kernel_memory: 5500M

eth1_github_external_user_pubkeys:
  - garyschulte
  - jflo
  - fab-10
  - matkt
  - gezero

# websocket with /ws suffix
eth1endpoint_ws: ws://127.0.0.1:8546/ws

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

eth1_env:
  JAVE_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  NATIVE_MEMORY_OPTS: "-XX:NativeMemoryTracking=detail -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics"

eth1_start_args: >
  --data-path="/eth1data/data"
  --genesis-file="/networkdata/besu_genesis.json"
  --network-id={{chainID}}
  --max-peers=100
  --rpc-http-enabled=true --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE
  --rpc-http-host=0.0.0.0
  --rpc-http-port={{eth1_rpc_port}}
  --engine-rpc-enabled=true
  --engine-rpc-port={{eth1_engine_port}}
  --engine-host-allowlist="*"
  --rpc-http-cors-origins="*"
  --rpc-ws-enabled=true --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE
  --rpc-ws-host=0.0.0.0
  --host-allowlist="*"
  --metrics-enabled
  --metrics-host=0.0.0.0
  --metrics-port={{eth1_metrics_port}}
  --p2p-enabled=true
  --miner-coinbase="{{fee_recipient}}"
  --p2p-host={{ansible_host}}
  {% if ansible_hostname == "mainnet-shadow-fork-10-lighthouse-besu-1" or ansible_hostname == "mainnet-shadow-fork-10-teku-besu-1" or ansible_hostname == "mainnet-shadow-fork-10-nimbus-besu-1" or ansible_hostname == "mainnet-shadow-fork-10-prysm-besu-1" or ansible_hostname == "mainnet-shadow-fork-10-lodestar-besu-1" %}
  --sync-mode=X_CHECKPOINT
  --data-storage-format="BONSAI"
  {% else %}
  --sync-mode=FAST
  --data-storage-format="FOREST"
  {% endif %}
  --engine-jwt-enabled
  --engine-jwt-secret=/jwtsecret
  --ethstats={{inventory_hostname}}:{{ethstats_password}}@{{ethstats_url}}:3000
  {% if (eth1_bootnode_enode is defined) and bootnode_enrs %}
  --bootnodes="{{ eth1_bootnode_enode | join(',') }}"
  {% endif %}

eth1_user_id: "1000:1000"
